modLoader = "javafml"
loaderVersion = "[${forge_version},)"
issueTrackerURL = "https://github.com/TropheusJ/construction/issues"
license = "MIT"

[[mods]]
modId = "construction"
version = "${version}"
displayName = "Construction"
authors = "TropheusJay"
description = '''
A multi-loader API for Create addons.
'''
logoFile = "icon.png"

[[dependencies.construction]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.construction]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.construction]]
modId="create"
mandatory=true
versionRange="${create_version}"
ordering="NONE"
side="BOTH"